### ISSUE TITLE
[bug] 네이버 카페에서 화질 적용이 안 되는 문제

### ISSUE THREAD

**Issue by porpyry** [occidere/improved-naver-video-plugin#9]
## 버그 내용
- 네이버 카페에서 화질 적용 기능이 간헐적으로 작동하지 않는 문제가 있습니다.
- 특히 매우 빠른 인터넷 환경에서 이러한 문제가 나타나는 것 같습니다.

## 상세
- main.js 스크립트 실행보다 iframe 로딩이 빠를 경우 eventListener가 등록되기 전에 load event가 발생하여 decorateAll() 함수가 실행되지 않는 것으로 보입니다.
  https://github.com/occidere/improved-naver-video-plugin/blob/8a424a114fe0eb9e1ec2d347c940c991585d04ca/js/main.js#L8-L10

## 재연
- 여러 번 테스트 결과 `init()` 시점에서 `getIframeDocument().readyState`[[1]](https://developer.mozilla.org/en-US/docs/Web/API/Document/readyState#different_states_of_readiness) 값이 `compelete`일 때 작동하지 않는 것을 확인했습니다.
- 빠른 인터넷 환경은 재연하기 어려워 반대로 다음과 같이 eventListener 등록이 iframe 로딩 이후에 이루어지도록 테스트해 보니 해당 문제가 발생하는 것을 확인했습니다.
  ```js
  async function init() {
      await sleep(5000); // delay 추가
      if (isCafe()) {
          getIframe().addEventListener('load', () => decorateAll());
      ...
  ```

## 해결 방안
- 다음과 같이 조치하여 race condition 없이[[2]](https://developer.mozilla.org/en-US/docs/Web/API/Document/DOMContentLoaded_event#checking_whether_loading_is_already_complete) 문제를 해결할 수 있을 것 같습니다.
  ```js
  async function init() {
      if (isCafe()) {
          if (getIframeDocument().readyState === "complete") {
              // iframe 로딩이 이미 완료됐을 경우 즉시 실행
              await decorateAll();
          } else {
              // iframe 로딩이 완료되지 않았을 경우 eventListener를 등록하여 로딩 완료 후 실행
              getIframe().addEventListener('load', () => decorateAll());
          }
      ...
  ```
- 테스트 결과 각각의 경우가 발생했으며 기능이 정상 작동하는 것을 확인했습니다.

**Comment by occidere** [comment]
안녕하세요 @porpyry 님, 상세한 분석 감사합니다!

안그래도 가끔가다 발생하는 것 같아서 고치려고 생각만 하고 있다가 결국 시간만 흘러갔는데 이렇게 솔루션까지 제안주셔서 감사해요!

혹시 시간이 허락하신다면 이왕 코드 작업해주신 것 PR 로까지 연결해주시는건 어떠신가요?

친절히 코드작업까지 해주셨는데 제가 그대로 가져가서 쓰기 보다는 @porpyry 님 흔적을 남겨주시는게 더 유의미할 것 같아서요 ㅎㅎ

혹시나 바쁘시거나 기타 이유로 불가하신 경우 말씀주시면 제가 직접 추가하겠습니다!

감사합니다 :)

**Comment by porpyry** [comment]
답변 주셔서 감사합니다! 너무 조그만 수정 제안이라 간단히 반영만 해주셔도 감사드리는데, 그렇게 말씀해주시니 좋은 기회라고 생각하고 PR 만들어 올려봤습니다. 처음 해보는 거라 잘 했는진 모르겠네요 ㅎㅎ

프로그램 잘 쓰고 있습니다. 좋은 프로그램 만들어주셔서 감사합니다!

**Comment by occidere** [comment]
Deployed as release-1.1.5 on Chrome extension store: https://github.com/occidere/improved-naver-video-plugin/releases/tag/release-1.1.5
😊
